---
# Only allow releases on the main branch (for 3k)
# releases for 2k are published manually.
branches:
  - name: main

plugins:
  - '@semantic-release/commit-analyzer'
  - '@semantic-release/git'
  - - "@semantic-release/exec"
    - publishCmd: |
        goreleaser release --clean --timeout 60m

tagFormat: '${version}'
