---
# Only allow releases on the main branch (for 3k)
# releases for 2k are published manually.
branches:
  - name: main

plugins:
  - '@semantic-release/commit-analyzer'
  - '@semantic-release/git'
  - - "@semantic-release/exec"
    - publishCmd: |
        VERSION=${nextRelease.version} GORELEASER_TIMEOUT=60m ./var/windows/goreleaser-release-with-msi.sh

tagFormat: '${version}'
