updatescreenshots:
	repo-common-take-screenshot mainpage-darkop http://localhost:1337/ 1024 680 --dark
	repo-common-take-screenshot mainpage-laptop http://localhost:1337/ 1024 680
	repo-common-take-screenshot mainpage-phone http://localhost:1337/ 600 1160
	repo-common-image-framer

.PHONY: updatescreenshots
