---
listenAddressSingleHTTPFrontend: 0.0.0.0:11337

logLevel: "WARN"
checkForUpdates: false
showFooter: false

actions:
  - title: Print a message
    shell: echo {{ message }}
    arguments:
      - name: message
        description: The message you want to print out on the shell.
        title: Your Message
        default: Hello World
        type: ascii_sentence
