[#log-levels]
= Logging - Actions

[NOTE]
There are two different types of logs in OliveTin - xref:advanced_configuration/logs.adoc[application logs] and xref:advanced_configuration/logs-actions.adoc[action logs]. This page is about the __action logs__, which are the logs that are generated by the actions that you run in OliveTin.

== Controlling access to see action logs

You can control access to action logs using **permissions**, which are assigned to actions.

=== Disabling logs for all users

[source, yaml]
----
logLevel: info

defaultPermissions:
  logs: false
----

=== Enabling logs for a specific ACL

[source, yaml]
----
logLevel: info

defaultPermissions:
  logs: false

accessControlLists:
  - name: admin
	matchUsernames:
	  - alice
	  - bob
	permissions:
	  logs: true

	addToEveryAction: true

actions:
  - title: My Action
	shell: echo "Hello World"
----

== Disabling the log viewer

You can disable the log viewer in the interface with xref::security/acl.adoc#_acls_and_policies_global[security policy configuration], using the defaults, or via an ACL. Examples are shown below for each of these methods. 

=== Disable log viewer for all users;

[source, yaml]
----
logLevel: info
defaultPolicy:
  showLogList: false
----

=== Disable log viewer expect for admin users

[source, yaml]
----
logLevel: info

defaultPolicy:
  showLogList: false
accessControlLists:
  - name: admin
	matchUsernames:
	  - alice
	  - bob
	policy:
	  showLogList: true
----

== See Also

* xref:action_customization/savelogs.adoc[Saving Action logs]
* xref:advanced_configuration/logs.adoc[Application Logs]
* xref:advanced_configuration/logs-calendar.adoc[Logs Calendar View]
