= Stylemods

There are several style modifications that some people like to use, which can easily be added to OliveTin. The configuration syntax in your `config.yaml` is very simple, and looks like this with a single style mod;

[source,yaml]
----
stylemods:
  - sm-side-icons
----	

You can add as many style mods as you like, but note that some of them may conflict with each other. The style mods are applied in the order they are listed, so if you have a conflict, the last one in the list will take precedence.

== Available Style Mods

* `sm-side-icons`: Display action buttons with the icons on the left hand side rather than above the text.
* `sm-imageicons-fullwidth`: Display image icons in full width, rather than the default size.
* `sm-transparent-header`: Make the header background transparent.
* `sm-transparent-footer`: Make the footer background transparent.

NOTE: The `sm-transparent-header` and `sm-transparent-footer` style mods often fix themes that were designed for OliveTin 2k.

The list of style mods on this page is maintained as new style modifications are added to OliveTin. 

== Feature history

* OliveTin `2025.7.29` introduced the ability to use style modifications, or "style mods".
